services:
  ros-kinetic:
    build:
      context: .
      dockerfile: dockerfile-ROS
    image: ros-kinetic:latest
    container_name: ros-kinetic
    stdin_open: true
    tty: true
    environment:
      # - DISPLAY=192.168.1.104:0.0
      - DISPLAY=${DISPLAY}  
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
