services:
  btraj-sim-melodic:
    build:
      context: .
      dockerfile: dockerfile
    hostname: btrajSim-Melodic  # 可选：设置容器主机名
    image: btraj-sim-melodic:latest
    container_name: btraj-sim-melodic
    stdin_open: true
    tty: true
    environment:
      # 对远端X服务器更稳的环境变量（可按需删改）
      - QT_X11_NO_MITSHM=1 
      - DISPLAY=${DISPLAY_IP:-192.168.1.104:0.0} # 自动检测Windows IP，默认值作为备用
    # - DISPLAY=${DISPLAY}  
    volumes:
      # X11 
      - /tmp/.X11-unix:/tmp/.X11-unix
      # 代码
      - ../Btraj:/root/catkin_ws/src/Btraj
      - ../plan_utils:/root/catkin_ws/src/plan_utils
      # license
      - ../mosek:/root/mosek

